kind: pipeline
type: docker
name: build-and-deploy

trigger:
  event:
    - tag

steps:
  - name: build-and-push-latest
    image: plugins/docker
    settings:
      repo: techbolt/spy-pixel
      tags: 
        - latest
        - ${DRONE_TAG}
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_auth_token

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_deploy_host
      username:
        from_secret: ssh_deploy_username
      key:
        from_secret: ssh_deploy_ssh_key
      script:
        - cd ~/s-Docker/spy-pixel/
        - docker-compose pull
        - docker-compose down
        - docker-compose up -d
        - sleep 2
        - docker-compose ps
        - echo "accessed from drone at $(date)" >> drone-access.log
